import { __assign, __makeTemplateObject } from "tslib";
import React from 'react';
import styled from 'styled-components';
var StyledPrinter = styled.i(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  &{background:linear-gradient(to left,currentColor 5px,transparent 0)no-repeat 0 10px/6px 2px, linear-gradient(to left,currentColor 5px,transparent 0)no-repeat 14px 10px/6px 2px, linear-gradient(to left,currentColor 5px,transparent 0)no-repeat 4px 4px/2px 2px;box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:24px;height:14px;border:2px solid transparent;border-bottom:0;box-shadow:inset 0 2px 0, inset 2px 2px 0, inset -2px 2px 0, inset -2px 2px 0}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:12px;border:2px solid;left:4px}&::before{height:6px;top:-4px}&::after{height:8px;top:8px}\n"], ["\n  &{background:linear-gradient(to left,currentColor 5px,transparent 0)no-repeat 0 10px/6px 2px, linear-gradient(to left,currentColor 5px,transparent 0)no-repeat 14px 10px/6px 2px, linear-gradient(to left,currentColor 5px,transparent 0)no-repeat 4px 4px/2px 2px;box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:24px;height:14px;border:2px solid transparent;border-bottom:0;box-shadow:inset 0 2px 0, inset 2px 2px 0, inset -2px 2px 0, inset -2px 2px 0}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:12px;border:2px solid;left:4px}&::before{height:6px;top:-4px}&::after{height:8px;top:8px}\n"])));
export var Printer = React.forwardRef(function (props, ref) {
    return (React.createElement(React.Fragment, null,
        React.createElement(StyledPrinter, __assign({}, props, { ref: ref }))));
});
var templateObject_1;
//# sourceMappingURL=Printer.js.map