import { __assign, __makeTemplateObject } from "tslib";
import React from 'react';
import styled from 'styled-components';
var StyledSun = styled.i(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:24px;height:24px;background:linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat 5px -6px/2px 6px, linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat 5px 14px/2px 6px, linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat -8px 5px/6px 2px, linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat 14px 5px/6px 2px;border-radius:100px;box-shadow:inset 0 0 0 2px;border:6px solid transparent}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:24px;height:2px;border-right:4px solid;border-left:4px solid;left:-6px;top:5px}&::before{transform:rotate(-45deg)}&::after{transform:rotate(45deg)}\n"], ["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:24px;height:24px;background:linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat 5px -6px/2px 6px, linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat 5px 14px/2px 6px, linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat -8px 5px/6px 2px, linear-gradient(to bottom,currentColor 4px,transparent 0)no-repeat 14px 5px/6px 2px;border-radius:100px;box-shadow:inset 0 0 0 2px;border:6px solid transparent}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:24px;height:2px;border-right:4px solid;border-left:4px solid;left:-6px;top:5px}&::before{transform:rotate(-45deg)}&::after{transform:rotate(45deg)}\n"])));
export var Sun = React.forwardRef(function (props, ref) {
    return (React.createElement(React.Fragment, null,
        React.createElement(StyledSun, __assign({}, props, { ref: ref }))));
});
var templateObject_1;
//# sourceMappingURL=Sun.js.map